name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - run: pnpm install

      - run: pnpm run build

      - name: Check build output
        run: |
          test -f dist/index.js || exit 1
          test -f dist/index.cjs || exit 1
          test -f dist/index.d.ts || exit 1
          echo "✅ All build artifacts present"
